./comparator \
    -desc "Searching for all executions allowed by Batty et al's simplified C11 model but disallowed by Lahav et al.'s strong release/acquire model." \
    -violates c11_sra.cat \
    -satisfies c11_simp.cat \
    -arch C \
    -events 6 \
    -expect 1 \
    -relacq \
    -simplepost \
    -satisfies c11_normws.cat \
    -totalsb \
    -iter
